version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: smythos-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: smythos_root_password
      MYSQL_DATABASE: smythos_db
      MYSQL_USER: smythos_user
      MYSQL_PASSWORD: smythos_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smythos-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psmythos_root_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: smythos-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - smythos-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  # SmythOS Application
  smythos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smythos-app
    restart: unless-stopped
    ports:
      - "5050:5050"
      - "5053:5053"
    env_file:
      - .env
    environment:
      # Override database URL to use internal MySQL container
      DATABASE_URL: mysql://smythos_user:smythos_password@mysql:3306/smythos_db
      # Override Redis to use internal Redis container (standalone mode)
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_SENTINEL_HOSTS: ""
      REDIS_MASTER_NAME: ""

    volumes:
      - smythos_data:/root/smythos-data
    networks:
      - smythos-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:5050/health && wget --no-verbose --tries=1 --spider http://localhost:5053/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      

networks:
  smythos-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  smythos_data:
    driver: local

