version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3001"

    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      restart_policy:
        condition: on-failure
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3001"

    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      restart_policy:
        condition: on-failure
  app3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3001"

    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      restart_policy:
        condition: on-failure
  app4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3001"

    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "5000:80"  # Expose Nginx on port 5000 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
