const errKeys = {
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  AGENT_LOCK_FAIL: 'AGENT_LOCK_FAIL',
  TEAM_OWNER_ONLY_ACTION: 'TEAM_OWNER_ONLY_ACTION',
  TEAM_HAS_ACTIVE_SUBSCRIPTION: 'TEAM_HAS_ACTIVE_SUBSCRIPTION',
  HAS_ACTIVE_SUBSCRIPTION: 'HAS_ACTIVE_SUBSCRIPTION',
  NOT_ENOUGH_PERMISSIONS: 'NOT_ENOUGH_PERMISSIONS',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',
  PAID_ONLY_FEATURE: 'PAID_ONLY_FEATURE',
  TEAM_HAS_SUBTEAMS: 'TEAM_HAS_SUBTEAMS',
  NOT_ALLOWED_TO_ACCESS_AGENT: 'NOT_ALLOWED_TO_ACCESS_AGENT',
  INVALID_PROMOTION_CODE: 'INVALID_PROMOTION_CODE',
  PROMOTION_CODE_FIRST_TIME_ORDER_ONLY: 'PROMOTION_CODE_FIRST_TIME_ORDER_ONLY',
  PROMOTION_CODE_NOT_VALID_FOR_TEAM: 'PROMOTION_CODE_NOT_VALID_FOR_TEAM',
};

export default errKeys;
